apiVersion: v1
kind: Service
metadata:
  name: random-api-service
  labels:
    app: random-api
spec:
  type: NodePort
  selector:
    app: random-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30080
